### ISSUE TITLE
other preprocessing

### ISSUE THREAD

**Issue by adelavega** [psychoinformatics-de/studyforrest-data-aligned#1]
hi @mih,
feel free to close this issue immediately, just a quick question.

has any other preprocessing been applied to these data? and to be clear, the bold timeseries in this repo have been aligned into standard MNI space?

I'm just running some early tests of neuroscout and need preprocessed data.

thanks

**Comment by mih** [comment]
None other than motion correction using a subject-specific template image. See code/avmovie_motion_correction.submit for the entry point to the respective code that does it.
